import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { defineConfig, type Plugin } from 'vite'
import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

// Injects the static portfolio snapshot (public/snapshot.html, generated by
// `npm run snapshot`) into index.html so every SPA route serves real,
// readable content to AI scrapers that don't run JavaScript.
function aiSnapshot(): Plugin {
  return {
    name: 'ai-snapshot',
    transformIndexHtml(html) {
      const file = resolve(__dirname, 'public/snapshot.html')
      if (!existsSync(file)) return html.replace('<!--AI_SNAPSHOT-->', '')
      const body = readFileSync(file, 'utf8').match(/<body[^>]*>([\s\S]*?)<\/body>/i)?.[1] ?? ''
      const block =
        `<main id="ai-content" aria-label="Moonsto portfolio snapshot (static)">\n` +
        `${body.trim()}\n` +
        `<p>Static version: <a href="/snapshot.html">moon-sto.web.app/snapshot.html</a></p>\n` +
        `</main>`
      return html.replace('<!--AI_SNAPSHOT-->', block)
    },
  }
}

export default defineConfig({
  plugins: [tailwindcss(), react(), aiSnapshot()],
})
